version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/dev.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/dev.txt" }}

      - run:
          name: Run unittest
          command: |
            . venv/bin/activate
            make test
          environment:
            FLASK_ENV: testing
            PROJECT_ROOT_FOR_DYNACONF: src.configs

      - run:
          name: Check pep8
          command: |
            . venv/bin/activate
            make lint

      - store_artifacts:
          path: test-reports
          destination: test-reports
